name: Copy Folder Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy folder
        run: |
          cp -r frontend docs

      - name: Verify copy
        run: |
          ls -la docs